export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST"
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS"
export const GET_BOOKS_FAILURE = "GET_BOOKS_FAILURE"

// export const ADD_TODOS_REQUEST = "ADD_TODOS_REQUEST"
// export const ADD_TODOS_SUCCESS = "ADD_TODOS_SUCCESS"
// export const ADD_TODOS_FAILURE = "ADD_TODOS_FAILURE"